services:
  - type: web
    name: finance-dashboard-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: finance-dashboard-ui
    runtime: static
    rootDir: frontend
    buildCommand: "npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_URL
        value: "https://finance-dashboard-api.onrender.com"

databases:
  - name: finance-db
    plan: free
